print("¿Cómo invocar al Dios Dragón?")
print('Para invocar al Dios Dragón hay que:') 
print('1º.- Reunir las 7 Bolas de Dragón')
print('2º.- Y gritar: "¡Sal Shenlong, y concede nuestros deseos!"')
print("2º.- Y gritar: \"¡Sal Shenlong, y concede nuestros deseos!\"")